TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += khly2000.db
DATA += khly2000.proto

#=======================================
include $(TOP)/configure/RULES
